# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch

import torch
# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.3253, 0.2822, 0.1573, 0.0329, 0.6169, 0.6114, 0.7610],
        [0.8471, 0.3844, 0.0277, 0.6977, 0.9693, 0.5560, 0.3688],
        [0.6709, 0.2820, 0.5895, 0.6166, 0.5140, 0.6303, 0.3781],
        [0.1373, 0.7166, 0.3931, 0.4510, 0.1103, 0.7784, 0.6261],
        [0.8669, 0.9806, 0.8940, 0.7921, 0.0735, 0.3869, 0.6928],
        [0.3786, 0.7003, 0.6370, 0.0260, 0.9671, 0.4840, 0.8121],
        [0.3672, 0.8679, 0.4874, 0.4697, 0.4999, 0.5555, 0.4728]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor2 = torch.rand(1,7)
# Perform matrix multiplication

torch.mm(tensor, tensor2.T)

tensor([[1.2350],
        [1.3131],
        [1.5106],
        [1.4676],
        [2.3062],
        [1.7066],
        [1.5028]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
RANDOM_SEED = 0
# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(2, 3)
torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(2, 3)
print(f"tensor_A: {tensor_A}")
print(f"tensor_B: {tensor_B}")
# Matrix multiply tensors
torch.mm(tensor_A, tensor_B.T)

tensor_A: tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])
tensor_B: tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])


tensor([[0.8443, 0.3578],
        [0.3578, 0.5140]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [31]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)
torch.rand(3, 4, device="cuda")

tensor([[0.1272, 0.8167, 0.5440, 0.6601],
        [0.2721, 0.9737, 0.3903, 0.3394],
        [0.5451, 0.7312, 0.3864, 0.5959]], device='cuda:0')


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [39]:
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU

dev = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {dev}")
# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(2, 3, device = dev)
torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(2, 3, device = dev)

print(tensor_A)
print(tensor_B)

Device: cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [41]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.size()


(tensor([[0.9792, 0.8358],
         [0.8358, 1.4578]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [42]:
# Find max
print(torch.max(tensor_C))
# Find min
print(torch.min(tensor_C))

tensor(1.4578, device='cuda:0')
tensor(0.8358, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [44]:
# Find arg max
print(tensor_C.argmin())
# Find arg min
print(tensor_C.argmax())

tensor(1, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [45]:
# Set seed
torch.manual_seed(1234)
# Create random tensor
tensor = torch.rand(1, 1, 1, 10)
# Remove single dimensions
tensor_squeezed = tensor.squeeze()
# Print out tensors and their shapes
print(tensor, tensor.shape)
print(tensor_squeezed, tensor_squeezed.shape)

tensor([[[[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681,
           0.6738, 0.3315]]]]) torch.Size([1, 1, 1, 10])
tensor([0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681, 0.6738,
        0.3315]) torch.Size([10])
