<a href="https://colab.research.google.com/github/Alohadron/PyTorch-for-Deep-Learning-Bootcamp/blob/main/extras/self_exercices/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy (Numerical Python)

NumPy is a powerful open-source library for numerical coputing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical fucntions to operate on these data structures efficiently.

### Key Features of NumPy:

1. **N-dimensional Array (ndarray)**: NumPy's core feature is its efficient multi-dimensional array object, `ndarray`, which allows for fast array computations.

2. **Mathematical Functions**: Includes a wide range of functions for operations such as linear algebra, statistics, Fourier transforms, adn random number generation.

3. **Broadcasting**: Enables efficient operations on arrays of different shapes without explicit looping.

4. **Vectorization**: Uses optimized C and Fortran code under the hood to execute operations much faster than standart Python loops.

5. **Memory Efficiency**: Uses contiguous memory storage, making operations significantly faster than Python lists.

6. **Integration**: Works seamlessly with other scientific omputating libraries like SciPy, Pandas, Matplotlib.

In [1]:
# Example Usage

import numpy as np

# Creating an array
arr = np.array([1, 2, 3, 4, 5])

# Performing mathematical operations
print(arr * 2)

# Creating a 2D array (matrix)
matrix = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(matrix)) #  Computes the inverse of a matrix

[ 2  4  6  8 10]
[[-2.   1. ]
 [ 1.5 -0.5]]


## Basic steps

In [2]:
# Step 1: Installation

!pip install numpy

In [3]:
# Step 2: Understanding NumPy Arrays
# NumPy provides `ndarray`, a powerful multi-dimensional array object.

import numpy as np

# 1D Array
arr1 = np.array([1, 2, 3, 4, 5])

# 2D Array (Matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# 3D Array (Tensor)
arr3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(5,)
(2, 3)
(1, 3, 3)


In [4]:
# Step 3: Array Operations
# You can preform element-wise operations without loops.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(a ** 2)

[5 7 9]
[ 4 10 18]
[1 4 9]


In [5]:
# Step 4: Indexing & Slicig
# NumPy allows advanced indexing.

arr = np.array([[10, 20, 30], [40, 50, 60]])

print(arr[0, 1])
print(arr[:, 2]) # column
print(arr[0, :]) # row

20
[30 60]
[10 20 30]


In [6]:
# Step 5: Useful NumPy Functions

# Generating Arrays
np.zeros((3, 3)) # 3x3 matrix filled with 0s
np.ones((2, 4)) # 2x4 matrix filled with 1s
np.arange(1, 10, 2) # [1, 3, 5, 7, 9]
np.linspace(0, 1, 5) # [0., 0.25, 0.5, 0.75, 1.]
np.random.rand(3, 3) # 3x3 random numbers between 0 and 1

# Mathematical Functions
arr = np.array([1, 2, 3, 4])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr)) # standart deviation

10
2.5
1.118033988749895


In [7]:
# Step 6: Linear Algebra with NumPy
# NumPy has a build-in `linalg` module for linear algebra operations.

matrix = np.array([[2, 3], [1, 4]])
inverse = np.linalg.inv(matrix) # Inverce of a matrix
determinant = np.linalg.det(matrix) # Determinant
eigenvalues, eigenvectors = np.linalg.eig(matrix) # Eigenvalues & eigenvectors

print(f"Matrix: {matrix}")
print(f"\nInverse of the: {inverse}")
print(f"\nDeterminant: {determinant}")
print(f"\nEigenvalues: {eigenvalues}, Eigenvectors: {eigenvectors}")

Matrix: [[2 3]
 [1 4]]

Inverse of the: [[ 0.8 -0.6]
 [-0.2  0.4]]

Determinant: 5.000000000000001

Eigenvalues: [1. 5.], Eigenvectors: [[-0.9486833  -0.70710678]
 [ 0.31622777 -0.70710678]]


In [8]:
# Step 7: Reshaping & Broadcasting
# NumPy allows reshaping and broadcasting operations.

arr = np.array([1, 2, 3, 4, 5, 6])
print(f"Original: {arr}")
reshaped = arr.reshape((2, 3)) # Converts to 2x3 matrix
print(f"Reshaped: {reshaped}")

a = np.array(([1], [2], [3])) # Shape (3,1)
b = np.array([4, 5, 6]) # Shape (1,3)
print(f"\na + b = \n{a + b}") # Broadcasting (adds rach row to b)

Original: [1 2 3 4 5 6]
Reshaped: [[1 2 3]
 [4 5 6]]

a + b = 
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [9]:
# Step 8: Speed & Performance Optimiztion
# NumPy is much faster than Python lists due to vectorization.

#Using `timeit` to compare speed
import timeit

# Python list
python_time = timeit.timeit(stmt="[x**2 for x in range(1000)]", number=1000)

# NumPy Array
numpy_time = timeit.timeit(stmt="np.arange(1000)**2", setup="import numpy as np", number=1000)

print(f"Python List Time: {python_time:.5f}")
print(f"NumPy Time: {numpy_time:.5f}")

Python List Time: 0.24407
NumPy Time: 0.00459


## Practice! Try solving small challenges using NumPy.

In [10]:
# Challenge 1: Create a 5×5 matrix filled with zeros, except for the border, which should be filled with ones.

# Expected Output:
#[[1. 1. 1. 1. 1.]
 #[1. 0. 0. 0. 1.]
 #[1. 0. 0. 0. 1.]
 #[1. 0. 0. 0. 1.]
 #[1. 1. 1. 1. 1.]]

zeros = np.zeros((5, 5))
zeros[:, 0], zeros[:, -1], zeros[0, :], zeros[-1, :] = 1, 1, 1, 1
zeros

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# Challenge 2: Create a NumPy array with values from 1 to 10 and reverse it.

# Exprected output:
#[10  9  8  7  6  5  4  3  2  1]

arr = np.arange(1, 11, 1)
reversed = arr[::-1]
reversed

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [12]:
# Challenge 3: Find the Mean, Median, and Standard Deviation of the given array

arr = np.array([5, 10 ,15, 20 ,25])
mean = np.mean(arr)
median = np.median(arr)
std = np.std(arr)

print(f"Mean: {mean}\n")
print(f"Median: {median}\n")
print(f"Standard Deviation: {std}")

Mean: 15.0

Median: 15.0

Standard Deviation: 7.0710678118654755


In [13]:
# Challenge 4: Find Index of Maximum Value
# Given an array of random integers, find the index of the maximum value.

arr = np.array([12, 45, 67, 89, 23, 56])

max_value = np.argmax(arr)
max_value

3

In [14]:
# Challenge 5: Generate a random matrix
# Create a 4x4 matrix with random numbers between 0 and 1.

random_matrix = np.random.rand(4, 4)
random_matrix

array([[0.33011748, 0.88813676, 0.84197675, 0.03113742],
       [0.74640819, 0.56170774, 0.8833394 , 0.31434927],
       [0.7340857 , 0.95367675, 0.20052125, 0.73670716],
       [0.42868486, 0.88324718, 0.45963101, 0.27657453]])

In [15]:
# Challenge 6: Replace all even numbers with -1

# Given the array:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Exprected output: [1, -1, 3, -1, 5, -1, 7, -1, 9, -1]
arr[arr % 2 == 0] = -1

print(arr)

[ 1 -1  3 -1  5 -1  7 -1  9 -1]


In [16]:
# Challenge 7: Reshape and Flatten a Matrix
# Convert a 1D array of 12 elements into a 3x4 matrix, then flatten it back to 1D.

arr = np.arange(12)
matrix = np.reshape(arr, (3, 4))
flattened = np.ndarray.flatten(matrix)
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
# Challenge 8: Find unique values in their counts

arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4]
[1 2 3 4]


In [18]:
# Challenge 9: Matrix Multiplication

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.dot(A, B)
C

array([[19, 22],
       [43, 50]])

In [19]:
# Challenge 10: Find Missing Values in an Array
# Find the indices where the missing values (NaN) occur.

arr = np.array([1, 2, np.nan, 4, np.nan, 6])

nan_indices = np.where(np.isnan(arr))
nan_indices

(array([2, 4]),)

In [20]:
# Challenge 11: Create a checkboard Pattern
# Create an 8x8 NumPy array with a checkerboard pattern of `0s` and `1s`, where `1s` are at even indices

# Exprexted output:
# [[1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]]


arr = np.zeros((8, 8), dtype=int)
arr[::2, ::2] = 1
arr[1::2, 1::2] = 1
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [44]:
# Challenge 12: Normalize an Array (Feature Scaling)
# Given an array of random numbers, normalize it so that all valuea are between 0 and 1.

# Set random seed for reproducibility
# np.random.seed(42)

arr = np.random.randint(1, 101, size=(5, 5))
print("Original Array:\n", arr)

# Normalize the array using min-max scalling
arr_min = arr.min()
arr_max = arr.max()
normalized_arr = (arr - arr_min) / (arr_max - arr_min)

print("\nNormalized Array:\n", np.round(normalized_arr, 2))

Original Array:
 [[92 58 55 90 90]
 [62 23  9 12  1]
 [58  1 34 96 48]
 [89  1 16 61 64]
 [63 69 22 93 67]]

Normalized Array:
 [[0.96 0.6  0.57 0.94 0.94]
 [0.64 0.23 0.08 0.12 0.  ]
 [0.6  0.   0.35 1.   0.49]
 [0.93 0.   0.16 0.63 0.66]
 [0.65 0.72 0.22 0.97 0.69]]


In [52]:
# Challenge 13: Find the most frequent value in an Array
# Given an array, find the value that appears most frequently.

arr = np.array([1, 1, 0, 2, 2, 3, 3, 3, 4, 4, 4, 4, 2, 2, 2, 2, 5])

# Count occurrences of each value
counts = np.bincount(arr)
print(counts)

# Find the value with the highest count
most_frequent = np.argmax(counts)

print("Most frequent value:", most_frequent)

[1 2 6 3 4 1]
Most frequent value: 2


In [55]:
# Challenge 14: Create a random integer matrix with a fized seed
# Genereate a 5x5 matrix of random integers between 1 and 100, but ensure the random value stay the same every time the code runs.

import numpy as np

# Set random seed
np.random.seed(42)

# Generate a 5x5 matrix with random integers between 1 and 100
random_matrix = np.random.randint(1, 101, size=(5, 5))

print("Random Matrix:\n", random_matrix)

Random Matrix:
 [[ 52  93  15  72  61]
 [ 21  83  87  75  75]
 [ 88 100  24   3  22]
 [ 53   2  88  30  38]
 [  2  64  60  21  33]]


In [56]:
# Challenge 15: Extract all odd numbers from an array
# Given an array:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Extract all odd numbers without using a loop.
odd_numbers = arr[arr % 2 == 1]

print(f"Original array: {arr}\nOdd numbers: {odd_numbers}")

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Odd numbers: [1 3 5 7 9]


In [57]:
# Challenge 16: Compute the Euclidian distance between two vectors
# Given two NumPy arrays representing points in a 2D space, compute the Euclidean distance between them.

point1 = np.array([3, 4])
point2 = np.array([7, 1])

# Euclidian distance is the straight-line distance between two points in space. It is the most common way to measure distance in geometry.
# Euclidian distance formula: d = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

# Where is Euclidian Distance use?
# 1. Machine Learning - To measure similarity between data points (e.g., K-Nearest Neighbors)
# 2. Computer Vision - To compare image features
# 3. Physics & Robotics - For navigation and motion planning.

# Solution 1: Using NumPy functions
distance = np.linalg.norm(point2 - point1)
print("NumPy Functions Solution:", distance)

# Solution 2: Using the manual formula
manual_distance = np.sqrt(np.sum((point2 - point1) ** 2))
print("Manual Formula Solution:", manual_distance)



NumPy Functions Solution: 5.0
Manual Formula Solution: 5.0


In [58]:
# Challenge 17: Replace negative values with zero
# Given an array:
arr = np.array([-1, 2, -3, 4, -5, 6, -7, 8, 9, -10])

arr[arr < 0] = 0
print("Modified Array:", arr)

Modified Array: [0 2 0 4 0 6 0 8 9 0]


In [62]:
# Challenge 18: Stack two arrays horizontally and vertically
# Given two NumPy arrays:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Stack them horizontally to form a `2x4` matrix
# Stack them vertically to form a `4x2` matrix

# Will do that by using NumPy functions np.hstack() and np.vstack()

# Horizontal stack
h_stack = np.hstack((A, B))

# Vertical stack
v_stack = np.vstack((A, B))

print(f"Horizontal stack: \n{h_stack}\nVertical stack: \n{v_stack}")

Horizontal stack: 
[[1 2 5 6]
 [3 4 7 8]]
Vertical stack: 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [63]:
# Challenge 19: Create a 3x3 identity matrix without using np.eye()
# Normally, you'd use `np.eye(3)`, but try building it manually

# Expected output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

# Create a 3x3 matrix filled with zeros
prime_matrix = np.zeros((3, 3))

# Set the diagonal elements to 1
np.fill_diagonal(prime_matrix, 1)

prime_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
# Challenge 20: Find the row with the maximum sum in a matrix
# Given a `5x5` matrix of random integers, find the row index that has the highest sum.

# Set random seed
np.random.seed(42)

arr = np.random.randint(1, 50, size=(5, 5))
print("Matrix:\n", arr)

# Calculate the sum of each row
row_sums = np.sum(arr, axis=1)

# Find the index of the row with the maximum sum
max_sum_row_index = np.argmax(row_sums)
print("\nRow Index with maximum sum: ", max_sum_row_index)

Matrix:
 [[39 29 15 43  8]
 [21 39 19 23 11]
 [11 24 36 40 24]
 [ 3 22  2 24 44]
 [30 38  2 21 33]]

Row Index with maximum sum:  2


In [75]:
# Challenge 21: Create a spiral matrix
# Given `n = 4`, create the following spiral matrix

#  [[ 1  2  3  4]
#  [12 13 14  5]
#  [11 16 15  6]
#  [10  9  8  7]]

# To create a spiral matrix , we can simulate the process of filling the matrix in a spiral order (left to right, top to bottom, right to left, and bottom to top)
# Steps:
# 1. Initialize an empty matrix of size `n x n` filled with zeros
# 2. Start at the top-left corner and fill the matrix in a spiral order by updating the matrix elements one by one
# 3. Keep track of the boundaries (top, bootm, left, right) and progressively shrink them as you fill the matrix

import numpy as np

def create_spiral_matrix(n):
  # 1. Initialize an empty n x n matrix
  spiral_matrix = np.zeros((n, n), dtype=int)

  # Define the boundaries
  top, bottom, left, right = 0, n - 1, 0, n - 1

  num = 1
  while top <= bottom and left <= right:
    # Fill top row (left to right)
    for i in range(left, right + 1):
      spiral_matrix[top][i] = num
      num += 1
    top += 1

    # Fill right column (top to bottom)
    for i in range(top, bottom + 1):
      spiral_matrix[i][right] = num
      num += 1
    right -= 1

    # Fill bottom row (right to left)
    if top <= bottom:
      for i in range(right, left - 1, -1):
        spiral_matrix[bottom][i] = num
        num += 1
      bottom -= 1

    # Fill left column (bottom to top)
    if left <= right:
      for i in range(bottom, top - 1, -1):
        spiral_matrix[i][left] = num
        num += 1
      left += 1

  return spiral_matrix

n = 5
spiral_matrix = create_spiral_matrix(n)
spiral_matrix

array([[ 1,  2,  3,  4,  5],
       [16, 17, 18, 19,  6],
       [15, 24, 25, 20,  7],
       [14, 23, 22, 21,  8],
       [13, 12, 11, 10,  9]])